### ISSUE TITLE
more idiomatic code possible with ssbh_lib update

### ISSUE THREAD

**Issue by ScanMountGoat** [ssbucarlos/wifisafe_anim_splicer#1]
I added derives for `Clone` and `PartialEq` on the latest commit to main on the ssbh_lib repo. This should make the code a lot less verbose and easier to read. I would also recommend running `cargo fmt` and `cargo clippy` for some cleanup and helpful suggestions. 

In terms of testing, I would not recommend checking full in game files into source control. You can always remove the files in a commit, add them to the .gitignore, and just test the files locally. If you wanted to write unit tests, you could create `Anim` structs in test functions and hardcode the buffers for each track to some recognizable value like `0x333333...` to make the tests easier to write. Manually comparing the outputs with ssbh_lib_json or ssbh_data_json is also probably good enough for a simple project like this. 

```rust
// current code
let new_track = ssbh_lib::formats::anim::TrackV2{
    name: reference_track.name.clone(),
    flags: reference_track.flags,
    frame_count: reference_track.frame_count,
    transform_flags: reference_track.transform_flags,
    data_offset: current_offset as u32,
    data_size: reference_track.data_size
};

// struct update syntax
let new_track = ssbh_lib::formats::anim::TrackV2{
    data_offset: current_offset as u32,
    ..reference_track.clone()
};
```
It's nice to see someone incorporating ssbh_lib into a project. Let me know if you have any questions about using the library or run into any issues.

**Comment by ssbucarlos** [comment]
i just saw this issue today when i was bugfixing, thanks for the feedback ill be implementing it shortly
